#!/usr/bin/python3
# This Programm Write by Mr.nope
# BlueTooth Scan v1.0
import os
import time
import sys
import platform
try:
   from colorama import Fore,init
   init()
except ImportError:
    os.system("pip3 install colorama")
try:
   import bluetooth
except ModuleNotFoundError:
    os.system("apt intall bluetooth libbluetooth-dev")
    os.system("pip3 install pybluez")
    import bluetooth
system = platform.uname()[0]
End = '\033[0m'
run_Err = Fore.RED + "\nPlease, Run This Programm on " + Fore.GREEN + "Windows!\n" + End
banner = Fore.GREEN + """
WWWWWWWWWWWWWWWWWNOolloxO0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWk'     ..':lxk0XWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWW0:....        .'cxKWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWNXKK0Okdc;.      .cONWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWXKKXNNWMWWXOxo,.   .;kNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWNd'...',:okKNWWWNOl.   .:0WWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWNl.        .;dOKWWWKl.   .xNWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWN0kxdoc,.     .lKWWWO;   .oNWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWNXNNWWWNKd;.    .dNWWXc   .oNWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWXd,.',:oOXWWNO;.    lXWWXc   .xWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWK:       'dXWWX0l.   lNWW0,   ;KWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWKkdoc'    ,OWWWNl   .kWWWd.  .xWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWXXNWWXd'   ,0WWW0'   cNWWO'   lNWWWWWWWWWWWW
WWWWWWWWWWWWWXx;..'cOWWk.   oNWWX:   :XWWK,   cNWWWWWWWWWWWW
WWWWWWWWWWWWNd.     '0WX:   oNWWWO:';kNWWNk;':OWWWWWWWWWWWWW
WWWWWWWWWWWWNo.     'OWWKxoxXWWWWWNNNWWWWWWNNWWWWWWWWWWWWWWW
WWWWWWWWWWWWWXd,..':ONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWN00KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n""" + End
scan_help = """
--menu | Scan Menu
-s | Start Scanning
--help | Zscan Help
"""
def title():
    if system == 'Linux':
      os.system("printf '\033]2;BlueTooth Scan\a'")
    elif system == 'Windows':
        os.system("title BlueTooth Scan")
    else:
         print(run_Err)
         sys.exit()
def cls():
    if system == 'Linux':
      os.system("clear")
    elif system == 'Windows':
        os.system("cls")
    else:
        print(run_Err)
        sys.exit()

def main():
    title()
    cls()
    print(banner)
    try1()
def try1():
    try_to_start = input("\nDo you want to Start Scanning? [y/n] ")
    if try_to_start == 'y':
      start()
    elif try_to_start == 'n':
        try2()
    else:
         try1()
def try2():
    try_to_exit = input("\npress Enter...")
    if try_to_exit == '':
      ext()
    else:
        ext()
def ext():
    cls()
    print("\nStop !!!\n")
    sys.exit()
def start():
    cls()
    print(banner)
    dev = bluetooth.discover_devices(lookup_names = True, lookup_class = True)
    print("\nStart Scanning...")
    time.sleep(1)
    num_dev = len(dev)
    print("\n{} Device Found!".format(num_dev))
    for name, macaddr, numdev in dev:
       print("\n")
       print("\nDevice Name: {}".format(name))
       print("\nDevice Mac Address: {}".format(macaddr))
       print("\nDevice Class: {}".format(numdev))
       time.sleep(1)
       try3()
def try3():
    try_again = input("\nDo you want to try again? [y/n] ")
    if try_again == 'y':
      start()
    elif try_again == 'n':
        try2()
    else:
        try3()
def arg():
    if sys.argv[1] == '--menu':
      main()
    elif sys.argv[1] == '--help':
        print(scan_help)
    elif sys.argv[1].lower() == '-s' or sys.argv[1].lower() == '--s':
        os.system("title Zscan")
        print(banner)
        dev = bluetooth.discover_devices(lookup_names = True, lookup_class = True)
        print("\nStart Scanning...")
        time.sleep(1)
        num_dev = len(dev)
        print("{} Device Found!".format(num_dev))
        for name, macaddr, numdev in dev:
          print("\n")
          print("\nDevice Name: {}".format(name))
          print("\nDevice Mac Address: {}".format(macaddr))
          print("\nDevice Class: {}".format(numdev))
          time.sleep(1)
    else:
        print("\nArgument Not found!")
        print("Usage: python3 zscan --help\n") 
        sys.exit()
if __name__ == '__main__':
  try:
     arg()
  except IndexError:
      print("\nPlease, Usage: python3 zscan --help")
      sys.exit()
